# Generated by Django 3.1.7 on 2021-03-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_delivery_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='product_id',
            new_name='product',
        ),
    ]
