# Generated by Django 3.1.7 on 2021-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='message',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
    ]
