# Generated by Django 3.1.7 on 2021-04-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210403_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
    ]
