# Generated by Django 3.1.7 on 2021-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_employee_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='delivery_date',
            new_name='attendence_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
