# Generated by Django 3.1.7 on 2021-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_delivery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
