# Generated by Django 3.1.7 on 2021-04-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210410_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
